### ISSUE TITLE
Hard transition using RefreshControl in IOFlatlist

### ISSUE THREAD

**Issue by geertvansoest** [zhbhun/react-native-intersection-observer#10]
Hi,

We're using the `IOFlatlist` component to track Banner views in our FlatList components. These lists can be manually refreshed using the RefreshControl which is available in the regular FlatList component.

Unfortunately, today we found out that if the `refreshing` value returns to FALSE, there is no smooth transition. Instead, there's a hard "refresh" and all list items jumping back to the top. This seems no issue using the `IOScrollView` component. Is this a known issue and is there a solution for this?

I think this is also related to the component "remounts" every time a state value changes, as I also mentioned in #9.

```
const IOFlatlist = withIO(FlatList);

return (
   <IOFlatlist
      // @ts-ignore
      data={data}
      renderItem={({item, index}) => { ... }}
      style={styles.container}
      refreshControl={
        <RefreshControl
          refreshing={isLoading}
          onRefresh={async () => {
            await setIsLoading(true);
            await dispatch(getNews());
            await setIsLoading(false);
          }}
          colors={Colors.REFRESH_CONTROL_ANDROID}
          tintColor={Colors.REFRESH_CONTROL_IOS}
        />
      }
    />
```

Thanks in advance!

Kind regard,
Geert van Soest

**Comment by zhbhun** [comment]
It's same as issue https://github.com/zhbhun/react-native-intersection-observer/issues/9, try put `withIO` outside the component.
