### ISSUE TITLE
Documentation: improve readme 

### ISSUE THREAD

**Issue by freeboub** [zhbhun/react-native-intersection-observer#13]
It would be useful to indicate in Readme file that parent context (IOFlatList or IOScrollView) is mandatory to make the library working, maybe introduce withIO hook would be usefull

**Comment by Amnesthesia** [comment]
Just ran into this, spent quite some time debugging and trying to figure out why it's not working when I've already put it inside an Animated.ScrollView ...

**Comment by freeboub** [comment]
Yes and the other issue below is that it doesn't work if you use scrollView inside another scrollView. 
On my side I fixed my issue just by changing windowSize.

**Comment by zhbhun** [comment]
Thank you for your feedback. We have just released an updated version of the usage instructions. Regarding the issue of nested scrolling, it is currently not supported. We had considered implementing it, taking inspiration from the browser-side Intersection Observer polyfill, but unfortunately, I haven't had the time recently to develop new features.

**Comment by freeboub** [comment]
No problem, I just give you feedback because I had to go over the source code to understand its philosophy. Thank you anyway!

**Comment by jboz** [comment]
> Just ran into this, spent quite some time debugging and trying to figure out why it's not working when I've already put it inside an Animated.ScrollView ...

How have you solve this ?
